ptb_path: C:\Users\andrii.prysiazhnyk\Documents\data\sp_project\ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1\ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1
